title: Always have a positive attitude
email:
description: Keep Learning
author: Nitin Mahajan, MS, PhD
baseurl: ""
url: "https://n_mahajan.github.io"

# Social Profiles
twitter_username:
github_username: nitinmahajan20
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
